In [1]:
# import modules
import xlsxwriter
import random
import pandas as pd
import numpy as np

In [2]:
from dataframe_excel_charting import DataFrameExcelCharting

In [3]:
# import pandas as pd
expected_metrics_by_node_df = pd.DataFrame(
                                           columns=[
                                                    "Settlement_ID",
                                                    "Network_ID",
                                                    "Node_ID",
                                                    "lat",
                                                    "lon",
                                                    "Marginal_Population_Served",
                                                    "Population_Served",
                                                    "Marginal_Total_Demand",
                                                    "Total_Demand",
                                                    "Total_Transit",
                                                    "Tower_Cost",
                                                    "Radio_Cost",
                                                    "Power_Cost",
                                                    "Hop_Count",
                                                    "Single_Site_Failure_Effect",
                                                    "Node_Utility",
                                                    ]
                                           )
expected_metrics_by_node_df.loc[len(expected_metrics_by_node_df)] = [
                                                                    "PER_5_216:1",
                                                                    "lat_-15.092711061872_lon_-73.745867783712",
                                                                     "F1",
                                                                     -15.092711061872,
                                                                     -73.745867783712,
                                                                     0.0,
                                                                     0.0,
                                                                     0.0,
                                                                     0.0,
                                                                     26608.5,
                                                                     15000.0,
                                                                     2500.0,
                                                                     10000.0,
                                                                     np.nan,
                                                                     26608.5,
                                                                     np.nan,
                                                                     ]
expected_metrics_by_node_df.loc[len(expected_metrics_by_node_df)] = [
                                                                    "PER_5_216:1",
                                                                    "lat_-15.092711061872_lon_-73.745867783712",
                                                                     "N1",
                                                                     -15.090779,
                                                                     -73.720231,
                                                                     10000.0,
                                                                     10000.0,
                                                                     17739.0,
                                                                     17739.0,
                                                                     26608.5,
                                                                     11000.0,
                                                                     57300.0,
                                                                     10000.0,
                                                                     1.0,
                                                                     26608.5,
                                                                     1.0,
                                                                     ]
expected_metrics_by_node_df.loc[len(expected_metrics_by_node_df)] = [
                                                                    "PER_5_216:1",
                                                                    "lat_-15.092711061872_lon_-73.745867783712",
                                                                    "N2",
                                                                    -15.113981,
                                                                    -73.723150,
                                                                    4000.0,
                                                                    4000.0,
                                                                    5913.0,
                                                                    5913.0,
                                                                    5913.0,
                                                                    15000.0,
                                                                    24800.0,
                                                                    10000.0,
                                                                    2.0,
                                                                    5913.0,
                                                                    1.0,
                                                                    ]
expected_metrics_by_node_df.loc[len(expected_metrics_by_node_df)] = [
                                                                    "PER_5_216:1",
                                                                    "lat_-15.092711061872_lon_-73.745867783712",
                                                                    "N3",
                                                                    -15.121024,
                                                                    -73.682895,
                                                                    2000.0,
                                                                    2000.0,
                                                                    2956.5,
                                                                    2956.5,
                                                                    2956.5,
                                                                    28000.0,
                                                                    24800.0,
                                                                    10000.0,
                                                                    2.0,
                                                                    2956.5,
                                                                    1.0,
                                                                    ]
expected_metrics_by_node_df.loc[len(expected_metrics_by_node_df)] = [
                                                                    "PER_5_121:1",
                                                                    "lat_-15.05366466651_lon_-73.770922082143",
                                                                    "F2",
                                                                    -15.05366466651,
                                                                    -73.770922082143,
                                                                    0.0,
                                                                    0.0,
                                                                    0.0,
                                                                    0.0,
                                                                    2217.375,
                                                                    28000.0,
                                                                    5000.0,
                                                                    10000.0,
                                                                    np.nan,
                                                                    2217.375,
                                                                    np.nan,
                                                                    ]
expected_metrics_by_node_df.loc[len(expected_metrics_by_node_df)] = [
                                                                    "PER_5_121:1",
                                                                    "lat_-15.05366466651_lon_-73.770922082143",
                                                                    "N4",
                                                                    -15.027052,
                                                                    -73.775133,
                                                                    1000.0,
                                                                    1000.0,
                                                                    1478.25,
                                                                    1478.25,
                                                                    1478.25,
                                                                    15000.0,
                                                                    24800.0,
                                                                    10000.0,
                                                                    1.0,
                                                                    1478.25,
                                                                    1.0,
                                                                    ]
expected_metrics_by_node_df.loc[len(expected_metrics_by_node_df)] = [
                                                                    "PER_5_121:1",
                                                                    "lat_-15.05366466651_lon_-73.770922082143",
                                                                    "N5",
                                                                    -15.006327,
                                                                    -73.759684,
                                                                    500.0,
                                                                    500.0,
                                                                    739.125,
                                                                    739.125,
                                                                    739.125,
                                                                    28000.0,
                                                                    24800.0,
                                                                    10000.0,
                                                                    1.0,
                                                                    739.125,
                                                                    1.0,
                                                                    ]

In [4]:
expected_metrics_by_node_df.head()

,Settlement_ID,Network_ID,Node_ID,lat,lon,Marginal_Population_Served,Population_Served,Marginal_Total_Demand,Total_Demand,Total_Transit,Tower_Cost,Radio_Cost,Power_Cost,Hop_Count,Single_Site_Failure_Effect,Node_Utility
0,PER_5_216:1,lat_-15.092711061872_lon_-73.745867783712,F1,-15.092711,-73.745868,0.0,0.0,0.0,0.0,26608.500,15000.0,2500.0,10000.0,NaN,26608.500,NaN
1,PER_5_216:1,lat_-15.092711061872_lon_-73.745867783712,N1,-15.090779,-73.720231,10000.0,10000.0,17739.0,17739.0,26608.500,11000.0,57300.0,10000.0,1.0,26608.500,1.0
2,PER_5_216:1,lat_-15.092711061872_lon_-73.745867783712,N2,-15.113981,-73.723150,4000.0,4000.0,5913.0,5913.0,5913.000,15000.0,24800.0,10000.0,2.0,5913.000,1.0
3,PER_5_216:1,lat_-15.092711061872_lon_-73.745867783712,N3,-15.121024,-73.682895,2000.0,2000.0,2956.5,2956.5,2956.500,28000.0,24800.0,10000.0,2.0,2956.500,1.0
4,PER_5_121:1,lat_-15.05366466651_lon_-73.770922082143,F2,-15.053665,-73.770922,0.0,0.0,0.0,0.0,2217.375,28000.0,5000.0,10000.0,NaN,2217.375,NaN

In [38]:
import plotly.plotly as py
import pandas as pd

# df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_us_cities.csv')
df = expected_metrics_by_node_df
df.head()

df['text'] = df['Network_ID'] + df["Node_ID"]
limits = [(0,5000),(5001,10000),(10001,30000)]
colors = ["rgb(0,116,217)","rgb(255,65,54)","rgb(133,20,75)"]
cities = []
scale = 100

for i in range(len(limits)):
    lim = limits[i]
    df_sub = df[(df["Single_Site_Failure_Effect"] >= lim[0]) & (df["Single_Site_Failure_Effect"] <= lim[1])]
    city = dict(
        type = 'scattergeo',
        #locations = ["peru"],
        #locationmode = "country names",
        lon = df_sub['lon'],
        lat = df_sub['lat'],
        text = df_sub['text'],
        marker = dict(
            size = df_sub['Single_Site_Failure_Effect'] / scale,
            color = colors[i],
            line = dict(width=0.5, color='rgb(40,40,40)'),
            sizemode = 'area'
        ),
        name = '{0} - {1}'.format(lim[0],lim[1]) )
    cities.append(city)

layout = dict(
        title = 'Single Site Failure Effect',
        showlegend = True,
        geo = dict(
            scope='south america',
            projection=dict( type='equirectangular', scale = 1),
            showland = True,
            landcolor = 'rgb(217, 217, 217)',
            subunitwidth=1,
            countrywidth=1,
            subunitcolor="rgb(255, 255, 255)",
            countrycolor="rgb(255, 255, 255)"
        ),
    )

fig = dict( data=cities, layout=layout )
# py.iplot(fig, validate=False, filename='d3-bubble-map-populations' )
plotly.offline.plot(fig, validate=False, filename='peru-location.html')

'file:///Users/arthur/Documents/tensorflow/dataframe_excel_charting/src/peru-location.html'

In [22]:
df[(df["Single_Site_Failure_Effect"] >= 0) & (df["Single_Site_Failure_Effect"] <= 10000)]

,Settlement_ID,Network_ID,Node_ID,lat,lon,Marginal_Population_Served,Population_Served,Marginal_Total_Demand,Total_Demand,Total_Transit,Tower_Cost,Radio_Cost,Power_Cost,Hop_Count,Single_Site_Failure_Effect,Node_Utility,text
2,PER_5_216:1,lat_-15.092711061872_lon_-73.745867783712,N2,-15.113981,-73.723150,4000.0,4000.0,5913.000,5913.000,5913.000,15000.0,24800.0,10000.0,2.0,5913.000,1.0,lat_-15.092711061872_lon_-73.745867783712N2
3,PER_5_216:1,lat_-15.092711061872_lon_-73.745867783712,N3,-15.121024,-73.682895,2000.0,2000.0,2956.500,2956.500,2956.500,28000.0,24800.0,10000.0,2.0,2956.500,1.0,lat_-15.092711061872_lon_-73.745867783712N3
4,PER_5_121:1,lat_-15.05366466651_lon_-73.770922082143,F2,-15.053665,-73.770922,0.0,0.0,0.000,0.000,2217.375,28000.0,5000.0,10000.0,NaN,2217.375,NaN,lat_-15.05366466651_lon_-73.770922082143F2
5,PER_5_121:1,lat_-15.05366466651_lon_-73.770922082143,N4,-15.027052,-73.775133,1000.0,1000.0,1478.250,1478.250,1478.250,15000.0,24800.0,10000.0,1.0,1478.250,1.0,lat_-15.05366466651_lon_-73.770922082143N4
6,PER_5_121:1,lat_-15.05366466651_lon_-73.770922082143,N5,-15.006327,-73.759684,500.0,500.0,739.125,739.125,739.125,28000.0,24800.0,10000.0,1.0,739.125,1.0,lat_-15.05366466651_lon_-73.770922082143N5